name: step2bin
channels:
  - pytorch
  - lambouj
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - occwl=1.0
  - pytorch=1.8.1
  - dgl-cuda11.1=0.6.1=py39_0 
  - tqdm=4.59.0
  - numpy=1.21.6
  - pythonocc-core=7.5.1

